name: report_cnd
description: "App de reportes CND (versión Flutter)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Paquetes que ya teníamos
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8

  # --- LÍNEA MODIFICADA ---
  # Bajamos la versión para que sea compatible con Firebase
  intl: ^0.18.1
  # --- FIN DE LA MODIFICACIÓN ---

  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- ESTA ES LA SECCIÓN CORREGIDA ---
  # 'flutter_lints' y 'flutterfire_cli' deben estar al mismo nivel
  # que 'flutter_test', no dentro de él.

  flutter_lints: ^5.0.0 # (Usamos la versión más reciente que tenías)

  flutterfire_cli: ^0.2.7 # (El nuevo paquete)
  # --- FIN DE LA CORRECCIÓN ---

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg